name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG (GitHub Default Dark Theme)
        uses: Platane/snk@v3
        with:
          github_user_name: jakebasa
          outputs: dist/github-contribution-grid-snake.svg?palette=github-dark

      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
